### ISSUE TITLE
less funky word wrapping

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-OWI/owi-blog#19]
the current dev prototype has words being broken into unconventional pieces, with no hyphens, when they occur at/across a line break. e.g., 
```
the point of this dem
o is to show how wor
ds are breaking oddl
y
```
there's surely some way to prevent this from happening.

**Comment by mwernimont** [comment]
@aappling-usgs Where does this happen? I'm looking at all the blogs and not seeing it, and probably am missing it.

**Comment by ldecicco-USGS** [comment]
Here's one on page 2 of the main blog pages:

![2016-06-21_8-57-02](https://cloud.githubusercontent.com/assets/1105215/16231978/47245ef6-378e-11e6-83c4-00aab0153ac7.png)

**Comment by ldecicco-USGS** [comment]
Also, I think any text within the individual text is getting wrapped funky, like the text is being forced to be 100% width, and breaking at exactly the letter (instead of breaking at a space):

![2016-06-21_8-58-55](https://cloud.githubusercontent.com/assets/1105215/16232029/7de71988-378e-11e6-8c83-81f14d1f8a7f.png)

**Comment by mwernimont** [comment]
Thats seems against how browsers normally act...it usually takes the whole word with it. I'll look into that

**Comment by mwernimont** [comment]
@ldecicco-USGS  #36 should fix this for what elements I could see effected by this oddity.

**Comment by ldecicco-USGS** [comment]
Almost done...just a
![2016-06-21_11-08-03](https://cloud.githubusercontent.com/assets/1105215/16237101/7cbaf52c-37a0-11e6-8c8d-c2d25ef82bee.png)
uthors still getting funkified.

**Comment by mwernimont** [comment]
Second to last PR should of taken care of this @ldecicco-USGS

**Comment by jread-usgs** [comment]
we want the funk. gotta have that funk.
